### ISSUE TITLE
eslint autofix doesn't fire

### ISSUE THREAD

**Issue by kakajansh** [nuxt-community/eslint-module#12]
eslint autofix fires when manually extended build in `nuxt.config.json`
```
build: {
  extend(config, ctx) {
    config.module.rules.push({
      enforce: "pre",
      test: /\.(js|vue)$/,
      loader: "eslint-loader",
      exclude: /(node_modules)/,
      options: {
        fix: true
      }
    })
  }
}
```

but below code doesn't work
```
devModules: [
  '@nuxtjs/eslint-module'
],

eslint: {
  fix: true
},
```
nor
```
devModules: [
  ['@nuxtjs/eslint-module', { fix: true }]
],
```

fresh nuxt project v2.8.1

**Comment by ricardogobbosouza** [comment]
Hi @kakajansh 
Can you either provide repository or a GIF of the blink ?

**Comment by kakajansh** [comment]
I created new app with `npx create-nuxt-app`. It turns out that it didn't pull the latest version of nuxt-app. So there was installed `"@nuxtjs/eslint-module": "^0.0.1"` version. Upgrading deps resolves issue 👍

```zsh
➜  npx create-nuxt-app nuxt-app
npx: installed 379 in 51.567s
create-nuxt-app v2.8.0
✨  Generating Nuxt.js project in /nuxt-app
? Project name nuxt-app
? Project description My divine Nuxt.js project
? Author name Kakajan SH
? Choose the package manager Npm
? Choose UI framework None
? Choose custom server framework None (Recommended)
? Choose Nuxt.js modules
? Choose linting tools ESLint
? Choose test framework None
? Choose rendering mode Single Page App
```

Maybe some related issues on [create-nuxt-app](https://github.com/nuxt/create-nuxt-app) repo:
 - [outdated dependencies in newly created app](https://github.com/nuxt/create-nuxt-app/issues/287)
 - [linting doesn't work properly](https://github.com/nuxt/create-nuxt-app/issues/290)
 - [install with npx create-nuxt-app, always install old version (v2.3.4)](https://github.com/nuxt/create-nuxt-app/issues/290)

**Comment by begueradj** [comment]
How did you fix this ? I have the same issue

**Comment by ricardogobbosouza** [comment]
@begueradj check version `@nuxtjs/eslint-module`

**Comment by tetreault** [comment]
`npx create-nuxt-app` still is using < v1.1.0

**Comment by bf** [comment]
I have the same issue, and my @nuxtjs/eslint-module is version 3.0.1

**Comment by metasean** [comment]
@ricardogobbosouza - I know this is an old issue, but I'm running into this with `@nuxtjs/eslint-module` `3.0.2`.  

Based on the fact that I'm running the latest published version and, in combination with @bf's comment, I really don't think the solution is "use the latest version".  

Unfortunately, I haven't figured out a solution.  If you have bandwidth to dig into this, doing so would be appreciated!

**Comment by kissu** [comment]
@metasean what's the issue with using the latest version?
