### ISSUE TITLE
support typescript file

### ISSUE THREAD

**Issue by calcoc** [nuxt-community/eslint-module#16]
https://github.com/nuxt/eslint-config
I found that typescript support was enabled in some other libraries with code  below, I would like to be able to process .ts files as well.
```
this.extendBuild((config, ctx) => {
    if (ctx.isDev && ctx.isClient) {
      config.module.rules.push({
        enforce: 'pre',
        test: /\.(js|vue)$/,
        ...
      })
    }
  })
```
```
this.extendBuild((config, ctx) => {
    if (ctx.isDev && ctx.isClient) {
      config.module.rules.push({
        enforce: 'pre',
        test: /\.(ts|js|vue)$/,
        ...
      })
    }
  })
```
Can you enable this changes or should I make a pull request?
Looking forward for your assistance.
Best regards.

**Comment by ricardogobbosouza** [comment]
@calcoc Thanks for the request.
Will be in version v1.2.0 see #17

**Comment by calcoc** [comment]
Thank you for your quick response.
It will help us a lot. 
Best regards.
