### ISSUE TITLE
The 'request' argument must be string. Received type undefined

### ISSUE THREAD

**Issue by mrleblanc101** [nuxt-community/eslint-module#20]
Hi,
When enabling autofix, I get this error:
```The 'request' argument must be string. Received type undefined```.
```
    buildModules: [
        '@nuxtjs/eslint-module',
        {
            fix: true,
        },
    ],
```
If i remove the config object, the problem disapear

**Comment by mrleblanc101** [comment]
I think I understood, if I am using Nuxt < 2.9.0, I can't define inline option and must use eslint object ?

**Comment by ricardogobbosouza** [comment]
@mrleblanc101 Your configuration is wrong, try this:
```js
buildModules: [
  ['@nuxtjs/eslint-module', { fix: true }],
],
```

**Comment by mrleblanc101** [comment]
You are right 😅
