### ISSUE TITLE
Eslint-module lints also `.nuxt` and other ignored folders

### ISSUE THREAD

**Issue by samuells** [nuxt-community/eslint-module#22]
Does the `@nuxtjs/estlint-module` read the `.eslintignore` file from the root of the project?

**Comment by ricardogobbosouza** [comment]
Hi @samuells,
The `@nuxtjs/estlint-module` only registers `eslint-loader` which executes `eslint` .
If you have any problems, please provide a repository to reproduce.

**Comment by louisremi** [comment]
In my project I had no problem getting .eslintignore to be taken into account
