### ISSUE TITLE
Question: Is it possible to lint nuxt.config.js and .eslintrc.js on hot reload?

### ISSUE THREAD

**Issue by albertpratomo** [nuxt-community/eslint-module#27]
The hot-reload lint works fine for component files.

But I can't get it to automatically lint `nuxt.config.js` and `.eslintrc.js` file. Is this possible?

**Comment by ricardogobbosouza** [comment]
Hi @albertpratomo at the moment it is not possible, you will have to run it manually.
This module uses the [eslint-loader](https://github.com/webpack-contrib/eslint-loader).

Probably in its next major version it will be modified to use the [eslint-webpack-plugin](https://github.com/webpack-contrib/eslint-webpack-plugin) that will give you this possibility.
