### ISSUE TITLE
ESlint stops working when switching to version 3

### ISSUE THREAD

**Issue by Holiden** [nuxt-community/eslint-module#43]
Hello there!

When i use "@nuxtjs/eslint-module": "^2.0.0" i am getting errors and warnings in the console like these:

![image](https://user-images.githubusercontent.com/48956742/97580984-9a9d1f80-1a26-11eb-98ca-f34c3a61a47f.png)

But i decided to upgrade to version 3.0.0 and I stopped receiving notifications. What am I doing wrong?

**Comment by starzou** [comment]
Same here.

**Comment by starzou** [comment]
@ricardogobbosouza Any ideas?

**Comment by pascalmattes** [comment]
I have the same problem

**Comment by caoliren** [comment]
i have the same problem

**Comment by libingqin** [comment]
I have the same problem

**Comment by ricardogobbosouza** [comment]
Problem on https://github.com/webpack-contrib/eslint-webpack-plugin
I'm solving now

**Comment by ricardogobbosouza** [comment]
Waiting review https://github.com/webpack-contrib/eslint-webpack-plugin/pull/41

**Comment by ricardogobbosouza** [comment]
Resolved on v3.0.1
