### ISSUE TITLE
No linter errors when build project

### ISSUE THREAD

**Issue by evd3v** [nuxt-community/eslint-module#63]
Hello!

I have installed  `@nuxtjs/eslint-module@3.0.2`, with config `
  eslint: {
    lintDirtyModulesOnly: false,
    cache: false,
    failOnError: true
  }
`

When I call `nuxt dev` (with eslint problems in project) - errors appears in console and it blocks application.
However, when I call `nuxt build` - there are no problems and build makes success.

I need to prevent success build when eslint errors are exists.
How can I do that?

**Comment by evd3v** [comment]
Also, lint errors in nuxt.config.js file are ignored.

**Comment by ricardogobbosouza** [comment]
Hi @evd3v 
See https://github.com/nuxt-community/eslint-module/issues/60#issuecomment-919448303
