### ISSUE TITLE
npm link issue

### ISSUE THREAD

**Issue by vis97c** [nuxt-community/eslint-module#67]
Hi, just started using the bridge to test the migration of an ongoing project to the v3. Previously i had this problem were the linked packages were beign analyzed by eslint, the solution was to set the "webpack.resolve.symlinks" option to false.

```typescript
// nuxt object, v2 config
export default {
	build: {
		extend(config: any) {
			config.resolve.symlinks = false;
		},
	},
};
```

Now with the bridge while the extend function is executed, the webpack config change is not reflected, so the issue has resurfaced. Do you know how can i access the webpack config? i've already tried hooks but with no results. as of this moment i had to disable this plugin. Thanks in advance.

**Comment by ricardogobbosouza** [comment]
Working on support of [Nuxt 3 / Bridge](https://github.com/nuxt-community/eslint-module/issues/69#issuecomment-1040638868)
