### ISSUE TITLE
Nuxt3?

### ISSUE THREAD

**Issue by eMeRiKa13** [nuxt-community/eslint-module#68]
Hello,

Is-it module already working with Nuxt3? It's marked unknown here https://modules.nuxtjs.org/?q=eslint&orderBy=desc

Thank you

**Comment by Aperrix** [comment]
Hi, i have build a fresh install of Nuxt 3 and implement @nuxtjs/eslint exactly like with Nuxt 2 and it's working

**Comment by eMeRiKa13** [comment]
Awesome. Thank you @Aperrix

**Comment by Aperrix** [comment]
Let me know if you need a minimal reproduction example to help you
