### ISSUE TITLE
[kit] [compat] Using extendBuild in Nuxt 3 has no effect.

### ISSUE THREAD

**Issue by francisashley** [nuxt-community/eslint-module#75]
A change to nuxt-kit from a couple months ago is now causing `[kit] [compat] Using extendBuild in Nuxt 3 has no effect. Instead call extendWebpackConfig and extendViteConfig.` to show up in the console. This currently appears benign. I can confirm disabling the eslint module removed the message.

See https://bytemeta.vip/index.php/repo/viandwi24/nuxt3-awesome-starter/issues/8

**Comment by nathanchase** [comment]
Also see: 
https://github.com/viandwi24/nuxt3-awesome-starter/issues/8#issuecomment-1103209108

**Comment by ricardogobbosouza** [comment]
Nuxt3 Support in progress https://github.com/nuxt-community/eslint-module/pull/70

**Comment by ricardogobbosouza** [comment]
Released [v4.0.0](https://github.com/nuxt-community/eslint-module/releases/tag/v4.0.0)
