### ISSUE TITLE
What does this package do?

### ISSUE THREAD

**Issue by thisismydesign** [nuxt-community/eslint-module#77]
I read the readme and sadly have no idea what this package does.

> ESLint module for Nuxt.js

Does this run eslint during the build? Is it required for eslint to be able to navigate .vue files? Something more? Something else?

**Comment by ricardogobbosouza** [comment]
Hi @thisismydesign 
This package run `eslint` in development mode together with `nuxt`,
without the need to separately run the `eslint`

**Comment by DevDengChao** [comment]
@ricardogobbosouza May I ask when dose this module works ? How do we trigger it ?

**Comment by ricardogobbosouza** [comment]
Every time a file is changed

You can configure extensions and files:
https://github.com/nuxt-community/eslint-module#extensions
https://github.com/nuxt-community/eslint-module#files

You can also enable fix
https://github.com/nuxt-community/eslint-module#fix

**Comment by ricardogobbosouza** [comment]
It is worth remembering that this is a module and not a plugin or a configuration for eslint

**Comment by nerdygas** [comment]
@ricardogobbosouza None of these links work any more. Can you please provide updated links? TYSM!
