### ISSUE TITLE
configuration file not working with nuxt 3

### ISSUE THREAD

**Issue by nerdygas** [nuxt-community/eslint-module#84]
Hello, currently using nuxt v3.2, and trying the eslint module v4.0.1

Issue - .eslintrc.js uses the module.exports syntax which doesn't work any more with nuxt 3

Ask - Needed a working example for nuxt 3 including the instructions to run the eslint.

Thank you

<img width="807" alt="image" src="https://user-images.githubusercontent.com/127453666/224181111-4cbf8a63-cadd-4491-bac2-ec600dd47e75.png">

<img width="298" alt="image" src="https://user-images.githubusercontent.com/127453666/224181177-90733b0f-f129-4e4e-8ff1-242c57bd29d4.png">

**Comment by ricardogobbosouza** [comment]
Hi @nerdygas 
Your configuration in .eslintrc.js is wrong

add `env: { node: true }`

**Comment by nidmidhalf** [comment]
Still doesn't help. Changed the syntax to Nuxt3 syntax. Here is my configuration file--

```
export default {
    root: true,
    env: {
        node: true,
    },
}
```


Here is the error on running the dev server


``` 
 ERROR  Cannot start nuxt:  Cannot read config file
Error: Unexpected token 'export'

```
